# Generated by Django 5.1.4 on 2026-09-16 03:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationCycle',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('name', models.CharField(max_length=100, verbose_name='회차명')),
                ('year', models.PositiveSmallIntegerField(verbose_name='평가연도')),
                ('starts_on', models.DateField(verbose_name='응답 시작일')),
                ('ends_on', models.DateField(verbose_name='응답 마감일')),
                (
                    'status',
                    models.CharField(
                        choices=[('DRAFT', '준비중'), ('OPEN', '진행중'), ('CLOSED', '마감')],
                        default='DRAFT',
                        max_length=10,
                        verbose_name='상태',
                    ),
                ),
                (
                    'primary_weight',
                    models.DecimalField(
                        decimal_places=2, default=70, max_digits=5, verbose_name='1차 반영비율'
                    ),
                ),
                (
                    'secondary_weight',
                    models.DecimalField(
                        decimal_places=2, default=30, max_digits=5, verbose_name='2차 반영비율'
                    ),
                ),
                (
                    'dept_baseline_score',
                    models.DecimalField(
                        decimal_places=2, default=70, max_digits=5, verbose_name='부서 가감 기준점'
                    ),
                ),
                (
                    'dept_adjust_factor',
                    models.DecimalField(
                        decimal_places=2, default=0.2, max_digits=5, verbose_name='부서 가감 계수'
                    ),
                ),
                (
                    'dept_adjust_limit',
                    models.DecimalField(
                        decimal_places=2, default=10, max_digits=5, verbose_name='부서 가감 한도'
                    ),
                ),
            ],
            options={
                'verbose_name': '평가 회차',
                'verbose_name_plural': '평가 회차',
                'ordering': ['-year', '-starts_on'],
                'constraints': [
                    models.CheckConstraint(
                        condition=models.Q(('starts_on__lte', models.F('ends_on'))),
                        name='cycle_starts_before_ends',
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name='EvaluationItem',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                (
                    'target_type',
                    models.CharField(
                        choices=[('EMPLOYEE', '개인'), ('DEPARTMENT', '부서')],
                        max_length=12,
                        verbose_name='대상유형',
                    ),
                ),
                ('code', models.CharField(max_length=30, verbose_name='항목코드')),
                ('title', models.CharField(max_length=200, verbose_name='문항')),
                ('description', models.TextField(blank=True, verbose_name='평가기준')),
                (
                    'weight',
                    models.DecimalField(decimal_places=2, max_digits=5, verbose_name='가중치'),
                ),
                ('max_score', models.PositiveSmallIntegerField(default=5, verbose_name='척도상한')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성여부')),
                (
                    'cycle',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='items',
                        to='evaluations.evaluationcycle',
                        verbose_name='회차',
                    ),
                ),
            ],
            options={
                'verbose_name': '평가 항목',
                'verbose_name_plural': '평가 항목',
                'ordering': ['cycle', 'target_type', 'order', 'id'],
                'indexes': [
                    models.Index(
                        fields=['cycle', 'target_type', 'is_active'],
                        name='evaluations_cycle_i_17bb7e_idx',
                    )
                ],
                'constraints': [
                    models.UniqueConstraint(
                        fields=('cycle', 'target_type', 'code'), name='uniq_item_cycle_type_code'
                    ),
                    models.CheckConstraint(
                        condition=models.Q(('weight__gt', 0)), name='item_weight_positive'
                    ),
                    models.CheckConstraint(
                        condition=models.Q(('max_score__gte', 1)), name='item_max_score_positive'
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name='EvaluatorAssignment',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                (
                    'target_type',
                    models.CharField(
                        choices=[('EMPLOYEE', '개인'), ('DEPARTMENT', '부서')],
                        max_length=12,
                        verbose_name='대상유형',
                    ),
                ),
                (
                    'cycle',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='assignments',
                        to='evaluations.evaluationcycle',
                        verbose_name='회차',
                    ),
                ),
                (
                    'primary_evaluator',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='primary_assignments',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='1차 평가자',
                    ),
                ),
                (
                    'secondary_evaluator',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='secondary_assignments',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='2차 평가자',
                    ),
                ),
                (
                    'target_department',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='as_target',
                        to='accounts.department',
                        verbose_name='평가대상(부서)',
                    ),
                ),
                (
                    'target_user',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='as_target',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='평가대상(직원)',
                    ),
                ),
            ],
            options={
                'verbose_name': '평가자 배정',
                'verbose_name_plural': '평가자 배정',
                'ordering': ['cycle', 'target_type', 'id'],
                'indexes': [
                    models.Index(
                        fields=['cycle', 'target_type'], name='evaluations_cycle_i_3634ed_idx'
                    ),
                    models.Index(
                        fields=['primary_evaluator'], name='evaluations_primary_cc64b2_idx'
                    ),
                    models.Index(
                        fields=['secondary_evaluator'], name='evaluations_seconda_996e18_idx'
                    ),
                ],
                'constraints': [
                    models.UniqueConstraint(
                        condition=models.Q(('target_user__isnull', False)),
                        fields=('cycle', 'target_type', 'target_user'),
                        name='uniq_assignment_cycle_user',
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(('target_department__isnull', False)),
                        fields=('cycle', 'target_type', 'target_department'),
                        name='uniq_assignment_cycle_department',
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ('target_department__isnull', True),
                                ('target_type', 'EMPLOYEE'),
                                ('target_user__isnull', False),
                            ),
                            models.Q(
                                ('target_department__isnull', False),
                                ('target_type', 'DEPARTMENT'),
                                ('target_user__isnull', True),
                            ),
                            _connector='OR',
                        ),
                        name='assignment_target_matches_type',
                    ),
                ],
            },
        ),
    ]
