# Generated by Django 5.1.4 on 2026-09-16 04:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('evaluations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationResponse',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                (
                    'round',
                    models.CharField(
                        choices=[('PRIMARY', '1차'), ('SECONDARY', '2차')],
                        max_length=10,
                        verbose_name='차수',
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[('DRAFT', '임시저장'), ('SUBMITTED', '제출완료')],
                        default='DRAFT',
                        max_length=10,
                        verbose_name='상태',
                    ),
                ),
                (
                    'submitted_at',
                    models.DateTimeField(blank=True, null=True, verbose_name='제출일시'),
                ),
                ('overall_comment', models.TextField(blank=True, verbose_name='종합의견')),
                (
                    'assignment',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='responses',
                        to='evaluations.evaluatorassignment',
                        verbose_name='배정',
                    ),
                ),
                (
                    'evaluator',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='responses',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='평가자',
                    ),
                ),
            ],
            options={
                'verbose_name': '평가지',
                'verbose_name_plural': '평가지',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationAnswer',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'score',
                    models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='점수'),
                ),
                ('comment', models.TextField(blank=True, verbose_name='의견')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                (
                    'item',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='answers',
                        to='evaluations.evaluationitem',
                        verbose_name='항목',
                    ),
                ),
                (
                    'response',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='answers',
                        to='evaluations.evaluationresponse',
                        verbose_name='평가지',
                    ),
                ),
            ],
            options={
                'verbose_name': '평가 답변',
                'verbose_name_plural': '평가 답변',
                'ordering': ['item__order', 'item_id'],
            },
        ),
        migrations.AddIndex(
            model_name='evaluationresponse',
            index=models.Index(
                fields=['evaluator', 'status'], name='evaluations_evaluat_0d6ec6_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='evaluationresponse',
            index=models.Index(
                fields=['assignment', 'round'], name='evaluations_assignm_2c0628_idx'
            ),
        ),
        migrations.AddConstraint(
            model_name='evaluationresponse',
            constraint=models.UniqueConstraint(
                fields=('assignment', 'round'), name='uniq_response_assignment_round'
            ),
        ),
        migrations.AddConstraint(
            model_name='evaluationanswer',
            constraint=models.UniqueConstraint(
                fields=('response', 'item'), name='uniq_answer_response_item'
            ),
        ),
        migrations.AddConstraint(
            model_name='evaluationanswer',
            constraint=models.CheckConstraint(
                condition=models.Q(('score__isnull', True), ('score__gte', 1), _connector='OR'),
                name='answer_score_min',
            ),
        ),
    ]
