# Generated by Django 5.1.4 on 2026-09-16 08:04

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('evaluations', '0002_evaluationresponse_evaluationanswer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationcycle',
            name='dept_adjust_factor',
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal('0.20'),
                max_digits=5,
                verbose_name='부서 가감 계수',
            ),
        ),
    ]
