# Generated by Django 5.1.4 on 2026-09-16 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('evaluations', '0002_evaluationresponse_evaluationanswer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreResult',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'primary_score',
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name='1차 환산점수',
                    ),
                ),
                (
                    'secondary_score',
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name='2차 환산점수',
                    ),
                ),
                (
                    'individual_score',
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name='개인 평가점수'
                    ),
                ),
                (
                    'department_score',
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name='부서 성과점수',
                    ),
                ),
                (
                    'department_adjustment',
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=6, verbose_name='부서 가감'
                    ),
                ),
                (
                    'final_score',
                    models.DecimalField(decimal_places=2, max_digits=6, verbose_name='최종 점수'),
                ),
                ('calculated_at', models.DateTimeField(auto_now=True, verbose_name='산출일시')),
                (
                    'cycle',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='score_results',
                        to='evaluations.evaluationcycle',
                        verbose_name='회차',
                    ),
                ),
                (
                    'department',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='score_results',
                        to='accounts.department',
                        verbose_name='산출시점 부서',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='score_results',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='피평가자',
                    ),
                ),
            ],
            options={
                'verbose_name': '점수 산출 결과',
                'verbose_name_plural': '점수 산출 결과',
                'ordering': ['-final_score', 'user__employee_no'],
                'indexes': [
                    models.Index(
                        fields=['cycle', 'department'], name='reports_sco_cycle_i_0ebf83_idx'
                    )
                ],
                'constraints': [
                    models.UniqueConstraint(fields=('cycle', 'user'), name='uniq_score_cycle_user'),
                    models.CheckConstraint(
                        condition=models.Q(('final_score__gte', 0), ('final_score__lte', 100)),
                        name='score_final_range',
                    ),
                ],
            },
        ),
    ]
