"""운영 환경 설정."""

from .base import *  # noqa: F403

DEBUG = False

# 운영에서는 반드시 환경 변수로 주입한다
SECRET_KEY = env('SECRET_KEY')  # noqa: F405
ALLOWED_HOSTS = env('ALLOWED_HOSTS')  # noqa: F405
CORS_ALLOWED_ORIGINS = env('CORS_ALLOWED_ORIGINS')  # noqa: F405

SECURE_SSL_REDIRECT = True
SECURE_HSTS_SECONDS = 31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
X_FRAME_OPTIONS = 'DENY'
SECURE_CONTENT_TYPE_NOSNIFF = True
